<?php

return [
    'cold_storage',
    'cold_storage_temperature',
    'denah',
    'foto_inspeksi_udang',
    'freezing_monitoring',
    'freezing_unit',
    'hasil_inspeksi_produk_sea_tiger',
    'kelas',
    'metal_detector',
    'monitoring_metal_detector',
    'pegawai',
    'pencatatan_suhu_udang',
    'pencucian',
    'penerimaan_dalam',
    'penerimaan_luar',
    'produk',
    'proses',
    'rak',
    'shipping_dalam',
    'storage',
    'stuffing',
    'supplier',
    'udang',
];